name = "Blogpaper"
license = "MIT"
licenselink = "https://github.com/NormandErwan/blogpaper/blob/master/LICENSE"
description = "A newspaper like blog theme for Hugo."
homepage = "https://normanderwan.github.io/blogpaper"
tags = ["blog", "minimalist"]
features = ["blog", "minimalist"]
min_version = "0.41"

[author]
  name = "Erwan Normand"
  homepage = "https://normanderwan.fr"
