author:
  name: Erwan Normand
baseURL: https://normanderwan.github.io/Blogpaper/
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Example site for the Hugo's Blogpaper theme
title: Blogpaper
theme: Blogpaper
